# -*- coding: utf-8 -*-
"""credit card agglomerative

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-F93F3uDpoOY6lZkEfQjTknrfz6bRcgI
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering
import scipy.cluster.hierarchy as sch
from sklearn.impute import SimpleImputer

dataset = pd.read_csv('CC GENERAL.csv')
x = dataset.iloc[:, [13, 3]].values
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(x[:, :1])
x[:, :1] = imp.transform(x[:, :1])

den = sch.dendrogram(sch.linkage(x, method='ward'))
plt.show()

hc = AgglomerativeClustering(n_clusters=2, affinity = 'euclidean', linkage='ward')
yhc = hc.fit_predict(x)
plt.scatter(x[yhc == 0, 0], x[yhc == 0, 1], s=100, c='red', label='Cluster1')
plt.scatter(x[yhc == 1, 0], x[yhc == 1, 1], s=100, c='blue', label = 'Cluster2')
plt.legend()
plt.show()