# -*- coding: utf-8 -*-
"""Credit Card Data kmeans Clustering

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jWi2WavYatBfckpnd955jkuj68_nJmtG
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans

dataset = pd.read_csv('CC GENERAL.csv')
x = dataset.iloc[:, [13, 3]].values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, [0,1]])
x[:, [0,1]] = imputer.transform(x[:, [0,1]])

WCSS = []
for i in range(1, 11):
  km = KMeans(n_clusters=i, init='k-means++', random_state=0)
  km.fit(x)
  WCSS.append(km.inertia_)

plt.plot(range(1, 11), WCSS)

km = KMeans(n_clusters=4, init='k-means++', random_state=0)
ykm = km.fit_predict(x)

plt.scatter(x[ykm == 0, 0], x[ykm == 0, 1], s=100, c='red', label='Cluster1')
plt.scatter(x[ykm == 1, 0], x[ykm == 1, 1], s=100, c='blue', label = 'Cluster2')
plt.scatter(x[ykm == 2, 0], x[ykm == 2, 1], s=100, c='green', label='Cluster3')
plt.scatter(x[ykm == 3, 0], x[ykm == 3, 1], s=100, c='yellow', label='Cluster4')
plt.scatter(km.cluster_centers_[:, 0], km.cluster_centers_[:, 1], s=300, c='orange', label='Centroids')
plt.title('Clusters of Customers')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.legend()
plt.show()